name: Build and Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t getting-started-app:latest .

    - name: Save Docker image to tar file
      run: |
        docker save getting-started-app:latest -o getting-started-app.tar

    - name: ssh into server
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Copy Docker image to server
      run: scp -o StrictHostKeyChecking=no -i ${{ secrets.SERVER_SSH_KEY }} getting-started-app.tar ${{ vars.AWS_USER }}@
        

    - name: SSH to Server and Deploy
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: 35.155.230.77
        username: ${{ vars.AWS_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker load -i /home/${{ vars.AWS_USER }}/getting-started-app.tar
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 80:80 getting-started-app:latest
